apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  revisionHistoryLimit: 0 
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: MESSAGE
            value: "Hello from App 1 !"
