apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 8888
    protocol: TCP
    name: http
  selector:
    app: wil-playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  revisionHistoryLimit: 0 
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
        imagePullPolicy: IfNotPresent
